### ISSUE TITLE
Clarification of "make prog" vs "make prog_flash" and the J6 header on the board.

### ISSUE THREAD

**Issue by secworks** [damdoy/ice40_ultraplus_examples#3]
Aloha!

Great project and collection of examples for how to utilize the iCE40 UltraPlus features! I just tested it with the breakout board and it worked almost without any problems. One small thing that caught me was "make prog" vs "make prog_flash" and how the board is configured out of the box from Lattice.

When I first tried "make prog", nothing happened. But "make prog" did. After reading the documentation for the board (The iCE40 UltraPlus Breakout Board iCE40 User Guide) it was quite obvious that I had to move the straps at J6 from horizontal to vertical orientation. With this change "make prog" works. I wold suggest adding a short comment in the README about checking J6 on the board and possibly set it in the desirable configuration.

The following link will allow downloading of the document:
https://www.latticesemi.com/view_document?document_id=51987

**Comment by damdoy** [comment]
Hello,

`make prog` will program the internal memory of the Ice40 Ultraplus. Since this memory is volatile, it will get erased every time the board is powered down.
`make prog flash` will program the separate flash chip on the breakout board, which will hold the data, however the FPGA will not be able to communicate through the USB using the SPI in this mode. A power cycle may be needed.

Indeed the orientation of the jumpers on J6 will decide whether the internal memory or the flash will be programmed, by redirecting the SPI lines.
![image](https://user-images.githubusercontent.com/11064332/113777860-f2555a80-972b-11eb-8531-1d6c7d273585.png)
(from Breakout board schematic)

For most of my tests where I wanted to do changes quickly I used the internal memory of the ice40. However the flash should work as well when the jumpers are set horizontally on J6. Looking at the schematic I see that J7 is also required for the flash to work.

But I fully agree that some explanation on how the flash and the internal memory work on the Breakout board is necessary because I also had a hard time to understand it completely when I started this project.

**Comment by secworks** [comment]
Aloha!
Great writeup, it matches my understanding of how the board works. I suggest that you simply take the text you wrote in the response above and add to the README. That will help other users immensely.

**Comment by secworks** [comment]
I took a stab at writing the clarification based on yor writeup:
https://github.com/secworks/ice40_ultraplus_examples/commit/fe10d0abe330dd6253a4df207affe82cb1130379

**Comment by damdoy** [comment]
Hello,
Thank you a lot incorporating the changes to the readme. I took a look at your readme I am really happy with it and want to incorporate them in this project, but there are two minor issues that I commented in the merge request before I can do that
